import React, { useEffect, useState } from 'react'
import Head from 'next/head'

interface User {
  id: number;
  name: string;
  email: string;
}

const ListUser = () => {
  const [users, setUsers] = React.useState<User[]>([]);
  const [message, setMessage] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(`https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users`, {
        method: 'GET',
      })
      let resJson = await res.json()
      if (res.status === 200) {
        React.useEffect(() => {
          // Fetch the list of users from the API and store it in the state
        }, [])
        setMessage('All users listed successfully')
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  

  return (
    <div>
      <Head>
        <title>Tenant Admin Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">All Users</h1>
        </div>
        <div>
          <h2></h2>
          <ul>
            {users.map(user => (
              <li key={user.id}>
                {user.name} ({user.email})
              </li>
            ))}
          </ul>
        </div>
        <div className="message">{message ? <p>{message}</p> : null}</div>
      </main>
    </div>
  )
}

export default ListUser
